services:
  postgres:
    image: postgres:16
    container_name: kc-postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - kc-net

  keycloak:
    image: quay.io/keycloak/keycloak:26.6.3
    container_name: keycloak
    command:
      - start-dev
      - --import-realm
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin

      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak_password

      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME: localhost
      KC_PROXY_HEADERS: xforwarded

      # Для dev-стенда отключаем кэш тем, чтобы изменения CSS/текстов были видны быстрее.
      KC_SPI_THEME_CACHE_THEMES: "false"
      KC_SPI_THEME_CACHE_TEMPLATES: "false"
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json:ro
      - ./keycloak/themes/company:/opt/keycloak/themes/company:ro
    depends_on:
      - postgres
    networks:
      - kc-net

  grafana:
    image: grafana/grafana:12.0.1
    container_name: grafana
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - keycloak
    networks:
      - kc-net

  # Optional: FreeIPA lab.
  # Запускать отдельно: docker compose --profile freeipa up -d freeipa
  #
  # Важно:
  # - лучше запускать на Linux, не на Docker Desktop;
  # - нужен privileged и cgroup mount;
  # - первый запуск может быть долгим.
  openldap:
    image: osixia/openldap:1.5.0
    container_name: openldap
    environment:
      LDAP_ORGANISATION: "Company"
      LDAP_DOMAIN: "company.local"
      LDAP_ADMIN_PASSWORD: "admin"
    ports:
      - "389:389"
    volumes:
      - openldap_data:/var/lib/ldap
      - openldap_config:/etc/ldap/slapd.d
    networks:
      - kc-net

  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: openldap
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8082:80"
    depends_on:
      - openldap
    networks:
      - kc-net

volumes:
  postgres_data:
  grafana_data:
  openldap_data:
  openldap_config:

networks:
  kc-net:
