[server]
http_port = 3000
root_url = http://localhost:3000/

[security]
admin_user = admin
admin_password = admin

[auth]
disable_login_form = false
oauth_auto_login = false

[auth.generic_oauth]
enabled = true
name = Keycloak
allow_sign_up = true
client_id = grafana
client_secret = grafana-secret
scopes = openid email profile roles

auth_url = http://localhost:8080/realms/company/protocol/openid-connect/auth
token_url = http://keycloak:8080/realms/company/protocol/openid-connect/token
api_url = http://keycloak:8080/realms/company/protocol/openid-connect/userinfo

login_attribute_path = "preferred_username"
email_attribute_path = "email"
name_attribute_path = "name"

# Берём роль из realm_access.roles в токене.
# Если есть grafana-admin -> Admin
# если есть grafana-editor -> Editor
# иначе Viewer.
role_attribute_path = "contains(realm_access.roles[*], 'grafana-admin') && 'Admin' || contains(realm_access.roles[*], 'grafana-editor') && 'Editor' || contains(realm_access.roles[*], 'grafana-viewer') && 'Viewer' || 'Viewer'"
role_attribute_strict = false
allow_assign_grafana_admin = true
skip_org_role_sync = false
